"""add_requirement_loop_count_to_leader_session

Revision ID: 0d15800c46b1
Revises: 600a5369112d
Create Date: 2026-06-11 19:55:19.734236

"""
from alembic import op
import sqlalchemy as sa

from migrations.safe_ops import SafeOperations


# revision identifiers, used by Alembic.
revision = '0d15800c46b1'
down_revision = '600a5369112d'
branch_labels = None
depends_on = None


def upgrade():
    safe_op = SafeOperations(op)
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段，设置默认值 0，再改为 NOT NULL
    safe_op.add_column('leader_sessions', sa.Column('requirement_loop_count', sa.Integer(), nullable=True))
    op.execute("UPDATE leader_sessions SET requirement_loop_count = 0 WHERE requirement_loop_count IS NULL")
    op.alter_column('leader_sessions', 'requirement_loop_count', nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leader_sessions', 'requirement_loop_count')
    # ### end Alembic commands ###
