"""add_shared_with_and_category_user_id

Revision ID: 5159c8bf2d21
Revises: d48a6f9187c2
Create Date: 2026-06-17 08:35:59.186800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from migrations.safe_ops import SafeOperations

# revision identifiers, used by Alembic.
revision = '5159c8bf2d21'
down_revision = 'd48a6f9187c2'
branch_labels = None
depends_on = None


def upgrade():
    safe_op = SafeOperations(op)
    # ### commands auto generated by Alembic - please adjust! ###
    safe_op.add_column('knowledge_categories', sa.Column('user_id', sa.Integer(), nullable=True))
    if safe_op.has_table('knowledge_categories'):
        # Drop the single-column unique constraint on key.
        # Two possible names exist: explicit ('uq_knowledge_category_key') and
        # auto-generated by create_all ('knowledge_categories_key_key').
        inspector = sa.inspect(op.get_bind())
        existing_constraints = {
            constraint['name']
            for constraint in inspector.get_unique_constraints('knowledge_categories')
        }
        for cname in ('uq_knowledge_category_key', 'knowledge_categories_key_key'):
            if cname in existing_constraints:
                op.drop_constraint(cname, 'knowledge_categories', type_='unique')
        safe_op.create_index('idx_knowledge_category_user', 'knowledge_categories', ['user_id'], unique=False)
        safe_op.create_unique_constraint('uq_knowledge_category_key_user', 'knowledge_categories', ['key', 'user_id'])
        safe_op.create_foreign_key(
            'fk_knowledge_categories_user_id_users',
            'knowledge_categories',
            'users',
            ['user_id'],
            ['id'],
        )
    safe_op.add_column('knowledge_documents', sa.Column('shared_with', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    safe_op = SafeOperations(op)
    safe_op.drop_column_if_exists('knowledge_documents', 'shared_with')
    if safe_op.has_table('knowledge_categories'):
        safe_op.drop_constraint_if_exists(
            'knowledge_categories',
            'fk_knowledge_categories_user_id_users',
            type_='foreignkey',
            local_cols=['user_id'],
            referent_table='users',
            remote_cols=['id'],
        )
        safe_op.drop_constraint_if_exists(
            'knowledge_categories',
            'uq_knowledge_category_key_user',
            type_='unique',
            local_cols=['key', 'user_id'],
        )
        safe_op.drop_index_if_exists('idx_knowledge_category_user', 'knowledge_categories')
        safe_op.create_unique_constraint('uq_knowledge_category_key', 'knowledge_categories', ['key'])
        safe_op.drop_column_if_exists('knowledge_categories', 'user_id')
    # ### end Alembic commands ###
