"""add leader report rating table

Revision ID: 600a5369112d
Revises: f7a8b9c0d1e2
Create Date: 2026-06-09 12:43:00.772817

"""
from alembic import op
import sqlalchemy as sa

from migrations.safe_ops import SafeOperations


# revision identifiers, used by Alembic.
revision = '600a5369112d'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade():
    safe_op = SafeOperations(op)
    # ### commands auto generated by Alembic - please adjust! ###
    safe_op.create_table('leader_report_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('leader_session_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['leader_session_id'], ['leader_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='unique_user_target_rating')
    )
    safe_op.create_index('idx_rating_conversation', 'leader_report_ratings', ['conversation_id'], unique=False)
    safe_op.create_index('idx_rating_created', 'leader_report_ratings', ['created_at'], unique=False)
    safe_op.create_index('idx_rating_session', 'leader_report_ratings', ['leader_session_id'], unique=False)
    safe_op.create_index('idx_rating_target', 'leader_report_ratings', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rating_target', table_name='leader_report_ratings')
    op.drop_index('idx_rating_session', table_name='leader_report_ratings')
    op.drop_index('idx_rating_created', table_name='leader_report_ratings')
    op.drop_index('idx_rating_conversation', table_name='leader_report_ratings')
    op.drop_table('leader_report_ratings')
    # ### end Alembic commands ###
